all:client6

client6:client6.cc
	g++ -o $@ $^ -std=c++11 -g -lpthread
client5:client5.cc
	g++ -o $@ $^ -std=c++11 -g -lpthread
client4:client4.cc
	g++ -o $@ $^ -std=c++11 -g -lpthread

client3:client3.cc
	g++ -o $@ $^ -std=c++11 -g -lpthread
client2:client2.cc
	g++ -o $@ $^ -std=c++11 -g -lpthread
client1:client1.cc
	g++ -o $@ $^ -std=c++11 -g -lpthread

# .PHONY:client
# client:client.cc
# 	g++ -o $@ $^ -std=c++11 -g -lpthread
	
# .PHONY:server
# server:server.cc
# 	g++ -o $@ $^ -std=c++11 -g -lpthread

# .PHONY:clean
# clean:
# 	rm -f client server